// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/buffer/save_fact": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buffer"
                ],
                "summary": "saveFact",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "auth_user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "comment",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "fact_time",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "indicator_to_mo_fact_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "indicator_to_mo_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "is_plan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "period_end",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "period_key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "period_start",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "value",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kpidrive.SaveFactResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/baseapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "baseapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "kpidrive.SaveFactResponse": {
            "type": "object",
            "properties": {
                "DATA": {
                    "type": "object",
                    "properties": {
                        "indicator_to_mo_fact_id": {
                            "type": "integer"
                        }
                    }
                },
                "MESSAGES": {
                    "type": "object",
                    "properties": {
                        "error": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "info": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "warning": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                },
                "STATUS": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EFFECTIVE MOBILE TEST TASK API",
	Description:      "API Server for effective mobile's test task",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
